paths:
  /auth:
    post:
      tags:
      - Authenticate
      description: Create new access token for user
      summary: Get access token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCredentials'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserCredentials'
      content: application/json
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /signup:
    post:
      tags:
      - Authenticate
      description: Create new user account with e-mail and password
      summary: Create new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCreatedResponse'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /my/user:
    get:
      tags:
      - My Data
      security:
      - token: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
  /my/collection:
    get:
      tags:
      - My Data
      security:
      - token: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionResponse'
info:
  title: TCG Game!
  version: 1.0.0
openapi: 3.0.2
components:
  schemas:
    UserCredentials:
      type: object
      properties:
        password:
          type: string
        username:
          type: string
          format: email
    TokenResponse:
      type: object
      properties:
        token:
          type: string
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
    SignupRequest:
      type: object
      properties:
        password:
          type: string
        username:
          type: string
          format: email
    UserCreatedResponse:
      type: object
      properties:
        message:
          type: string
    UserResponse:
      type: object
      properties:
        credits:
          type: integer
        cards:
          type: integer
        name:
          type: string
          format: email
    CollectionCardResponse:
      type: object
      properties:
        is_marketed:
          type: boolean
        price:
          type: integer
        url:
          type: string
        count:
          type: integer
        name:
          type: string
    CollectionResponse:
      type: object
      properties:
        owner:
          type: string
        collection:
          type: array
          items:
            $ref: '#/components/schemas/CollectionCardResponse'
  securitySchemes:
    token:
      type: http
      scheme: bearer
      bearerFormat: JWT
