paths:
  /test:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
  /test/db:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
info:
  title: TCG Game!
  version: 1.0.0
openapi: 3.0.2
components:
  schemas:
    Test:
      type: object
      properties:
        content:
          type: string
        id:
          type: integer
